#!/usr/bin/env node
const {
  User
} = require('../database');

const models = {
  User
};

async function migrate() {
  for (const i in models) {
    console.log(`Migrate ${i}`);
    await models[i].sync({ alter: true });
  }
  process.exit(0);
}

migrate().then((success)=>{
  console.log('success', success)
}).catch((e) => {
  console.log('ERROR', e)
});


